In [19]:
f = open('fileInput.txt', 'r')
lines = f.readlines()
N = int(lines[0])
bills = list(map(int, lines[1].strip().split(' ')))

In [22]:
def lemonadeChange(N, bills):
        # Code here
        numbills = dict()
        change = True
        for bill in bills:
            if bill in [10, 20]:
                if bill == 10 and numbills.get(5,0) > 0:
                    numbills[5] = numbills.get(5, 0)-1
                elif bill == 20 and numbills.get(5,0) > 0 and numbills.get(10,0) > 0:
                    numbills[10] = numbills.get(10, 0)-1
                    numbills[5] = numbills.get(5, 0)-1
                else:
                    return False, bill
            numbills[bill] = numbills.get(bill, 0)+1
        return True

In [24]:
lemonadeChange(N, bills)

(False, 20)

In [30]:
import numpy as np

In [38]:
img = np.zeros((32,32,3))
print(img.shape)
x = img.reshape((32*32*3,1))
print(x.shape)

(32, 32, 3)
(3072, 1)


In [84]:
a = np.random.random((3,4))
b = np.random.random((4,1))

c = np.zeros((3,4))

c = a*b.T

In [94]:
c

array([[1.03831990e-01, 4.14999061e-01, 1.00340362e-01, 3.74792494e-02],
       [7.96447956e-04, 8.16870276e-01, 2.05289712e-02, 2.90138200e-01],
       [5.06008232e-02, 8.59202452e-01, 6.84467371e-02, 6.19730682e-01]])

In [98]:
c.reshape(1,-1).shape

(1, 12)

In [73]:
a = np.array([[1,1],[1,-1]])
b = np.array([[2],[3]])
a+b

array([[3, 3],
       [4, 2]])

In [74]:
np.array?

In [105]:
x = '3'

In [107]:
assert x == '4', 'x should 3'

AssertionError: x should 3

In [111]:
np.random.rand(4,5)

array([[0.20058681, 0.44191039, 0.49335686, 0.98882615, 0.20796327],
       [0.95415342, 0.91839442, 0.85911084, 0.01789303, 0.65510449],
       [0.92939414, 0.530002  , 0.98175607, 0.19166032, 0.37263815],
       [0.85213119, 0.10452814, 0.66521497, 0.69818201, 0.70539339]])

In [112]:
np.sum(np.random.rand(4,5), axis=1).shape

(4,)